const KEY='kakis-acoustics-lab-v1';
const octave=[63,125,250,500,1000,2000,4000,8000];
const defaultMaterials=[{id:'rw5',name:'Mineral wool — 5,000',flow:5000},{id:'rw10',name:'Mineral wool — 10,000',flow:10000},{id:'rw16',name:'Mineral wool — 16,500',flow:16500}];
const defaultState={projectName:'New acoustic project',activeView:'dashboard',theme:'light',materials:defaultMaterials,designs:[{id:crypto.randomUUID(),name:'Ceiling absorber',layers:[{id:crypto.randomUUID(),type:'porous',thickness:100,flow:5000},{id:crypto.randomUUID(),type:'air',thickness:100}]}],activeDesign:0};
let state=load();
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultState)}}
let saveTimer;function save(){document.querySelector('#saveState').textContent='ინახება…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{localStorage.setItem(KEY,JSON.stringify(state));document.querySelector('#saveState').textContent='შენახულია'},250)}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function showView(id){state.activeView=id;$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#sidebar').classList.remove('open');save()}
$$('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-open]').forEach(b=>b.onclick=()=>showView(b.dataset.open));
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#projectName').value=state.projectName;$('#projectName').oninput=e=>{state.projectName=e.target.value;save()};
function applyTheme(){document.body.classList.toggle('dark',state.theme==='dark')}applyTheme();$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';applyTheme();save();drawChart()};
$('#openRoomNew').onclick=()=>window.open('room/index.html','_blank');
function design(){return state.designs[state.activeDesign]}
function renderLayers(){const d=design();$('#designName').value=d.name;$('#layers').innerHTML=d.layers.map((l,i)=>`<article class="layer" data-id="${l.id}"><div class="layer-top"><span class="layer-title">${l.type==='porous'?'Porous material':'Air gap'}</span><div class="layer-actions"><button data-up="${i}">↑</button><button data-down="${i}">↓</button><button data-delete="${i}">×</button></div></div><div class="layer-fields"><label>Thickness (mm)<input data-field="thickness" data-index="${i}" inputmode="decimal" value="${l.thickness}"></label>${l.type==='porous'?`<label>Flow resistivity<select data-field="flow" data-index="${i}">${state.materials.map(m=>`<option value="${m.flow}" ${Number(l.flow)===Number(m.flow)?'selected':''}>${m.name}</option>`).join('')}</select></label>`:''}</div></article>`).join('');
  $$('[data-field]').forEach(el=>el.oninput=e=>{const l=d.layers[+e.target.dataset.index];l[e.target.dataset.field]=Number(e.target.value)||0;save();calculate()});
  $$('[data-delete]').forEach(b=>b.onclick=()=>{d.layers.splice(+b.dataset.delete,1);renderLayers();save();calculate()});
  $$('[data-up]').forEach(b=>b.onclick=()=>move(+b.dataset.up,-1));$$('[data-down]').forEach(b=>b.onclick=()=>move(+b.dataset.down,1));
}
function move(i,dir){const a=design().layers,j=i+dir;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];renderLayers();save();calculate()}
$('#designName').oninput=e=>{design().name=e.target.value;save()};
$('#addLayer').onclick=()=>$('#layerModal').classList.remove('hidden');$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));
$$('.layer-choice').forEach(b=>b.onclick=()=>{design().layers.push(b.dataset.type==='porous'?{id:crypto.randomUUID(),type:'porous',thickness:50,flow:5000}:{id:crypto.randomUUID(),type:'air',thickness:50});$('#layerModal').classList.add('hidden');renderLayers();save();calculate()});
$('#newDesign').onclick=()=>{state.designs.push({id:crypto.randomUUID(),name:`Absorber ${state.designs.length+1}`,layers:[]});state.activeDesign=state.designs.length-1;renderLayers();calculate();save()};
$('#duplicateDesign').onclick=()=>{const c=structuredClone(design());c.id=crypto.randomUUID();c.name+=' copy';c.layers.forEach(l=>l.id=crypto.randomUUID());state.designs.push(c);state.activeDesign=state.designs.length-1;renderLayers();calculate();save()};
function cadd(a,b){return [a[0]+b[0],a[1]+b[1]]}function cmul(a,b){return [a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]]}function cdiv(a,b){const d=b[0]*b[0]+b[1]*b[1];return [(a[0]*b[0]+a[1]*b[1])/d,(a[1]*b[0]-a[0]*b[1])/d]}function cabs2(a){return a[0]*a[0]+a[1]*a[1]}function csin([x,y]){return [Math.sin(x)*Math.cosh(y),Math.cos(x)*Math.sinh(y)]}function ccos([x,y]){return [Math.cos(x)*Math.cosh(y),-Math.sin(x)*Math.sinh(y)]}
function matMul(A,B){return [[cadd(cmul(A[0][0],B[0][0]),cmul(A[0][1],B[1][0])),cadd(cmul(A[0][0],B[0][1]),cmul(A[0][1],B[1][1]))],[cadd(cmul(A[1][0],B[0][0]),cmul(A[1][1],B[1][0])),cadd(cmul(A[1][0],B[0][1]),cmul(A[1][1],B[1][1]))]]}
function layerMatrix(l,f){const rho=1.21,c=343,Z0=rho*c,w=2*Math.PI*f,d=l.thickness/1000;let Z=[Z0,0],k=[w/c,0];if(l.type==='porous'){const X=Math.max(1e-7,f*rho/Math.max(1,l.flow));Z=[Z0*(1+5.5*Math.pow(X,-.632)),Z0*(-8.43*Math.pow(X,-.632))];k=[w/c*(1+7.81*Math.pow(X,-.618)),w/c*(-11.41*Math.pow(X,-.618))]}const kd=[k[0]*d,k[1]*d],co=ccos(kd),si=csin(kd),jSi=[-si[1],si[0]];return [[co,cmul(jSi,Z)],[cdiv(jSi,Z),co]]}
function alphaAt(f){let M=[[[1,0],[0,0]],[[0,0],[1,0]]];for(const l of design().layers)M=matMul(M,layerMatrix(l,f));const Zin=cdiv(M[0][0],M[1][0]);const Z0=[1.21*343,0],R=cdiv([Zin[0]-Z0[0],Zin[1]],[Zin[0]+Z0[0],Zin[1]]);return Math.max(0,Math.min(1,1-cabs2(R)))}
let graphData=[];function calculate(){graphData=[];for(let i=0;i<=180;i++){const f=20*Math.pow(10000/20,i/180);graphData.push([f,alphaAt(f)])}const vals=octave.map(alphaAt);$('#octaveTable').innerHTML=`<table><tr>${octave.map(f=>`<th>${f} Hz</th>`).join('')}</tr><tr>${vals.map(v=>`<td><b>${v.toFixed(2)}</b></td>`).join('')}</tr></table>`;drawChart()}
function drawChart(){const c=$('#chart'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||920,h=Math.min(420,w*.46);c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);const dark=document.body.classList.contains('dark'),fg=dark?'#94a3b8':'#64748b',grid=dark?'#26344a':'#dbe3ed',accent='#06b6d4';ctx.clearRect(0,0,w,h);ctx.font='12px sans-serif';ctx.strokeStyle=grid;ctx.fillStyle=fg;for(let a=0;a<=1.001;a+=.2){const y=15+(1-a)*(h-45);ctx.beginPath();ctx.moveTo(48,y);ctx.lineTo(w-10,y);ctx.stroke();ctx.fillText(a.toFixed(1),12,y+4)}for(const f of [20,50,100,200,500,1000,2000,5000,10000]){const x=48+Math.log(f/20)/Math.log(10000/20)*(w-58);ctx.beginPath();ctx.moveTo(x,15);ctx.lineTo(x,h-30);ctx.stroke();ctx.fillText(f>=1000?(f/1000)+'k':f,x-8,h-8)}ctx.strokeStyle=accent;ctx.lineWidth=2.5;ctx.beginPath();graphData.forEach(([f,a],i)=>{const x=48+Math.log(f/20)/Math.log(10000/20)*(w-58),y=15+(1-a)*(h-45);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function renderMaterials(){ $('#materialCards').innerHTML=state.materials.map((m,i)=>`<article class="material-card"><h3>${m.name}</h3><p><b>${m.flow.toLocaleString()}</b> Pa·s/m²</p>${i>=defaultMaterials.length?`<button data-rm-mat="${i}">წაშლა</button>`:''}</article>`).join('');$$('[data-rm-mat]').forEach(b=>b.onclick=()=>{state.materials.splice(+b.dataset.rmMat,1);renderMaterials();renderLayers();save()})}
$('#addMaterial').onclick=()=>$('#materialModal').classList.remove('hidden');$('#saveMaterial').onclick=()=>{const name=$('#matName').value.trim(),flow=Number($('#matFlow').value);if(!name||!flow)return;state.materials.push({id:crypto.randomUUID(),name,flow});$('#materialModal').classList.add('hidden');$('#matName').value='';renderMaterials();renderLayers();save()};
window.addEventListener('resize',drawChart);showView(state.activeView);renderLayers();renderMaterials();calculate();
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');
